### ISSUE TITLE
Incorrect characters

### ISSUE THREAD

**Issue by novus57** [Integralist/ProVim#3]
Hello. Please, help me. After I copied .vimrc and .vim folder in my home directory, incorrect characters began to appear when I try to use vim keystrokes. Thanks in advance.
![selection_001](https://cloud.githubusercontent.com/assets/16938595/14585453/27c57212-047f-11e6-842e-ed39b5332d2a.png)

**Comment by novus57** [comment]
I use Ubuntu 14.04

**Comment by novus57** [comment]
I found that the problem was in this command: "set visualbell". To solve this I add this line "set t_vb=".

**Comment by Integralist** [comment]
Hi @novus57

Hmm, very strange that the visualbell setting would have caused that issue. 

It initially looked like you were missing the specific powerline fonts https://github.com/Integralist/ProVim/tree/master/fonts

But you reckon this problem is now resolved, is that correct? If so then let me know and I can close this issue.

Thanks for getting in contact with this bug. Much appreciated :-)

**Comment by novus57** [comment]
Thanks for answer. I installed this fonts but this doesn't help. Yes, you can close this issue. The problem is resolved.
