### ISSUE TITLE
E474

### ISSUE THREAD

**Issue by gregorydillon** [Integralist/ProVim#4]
```
Error detected while processing /home/gdillon/.vimrc:
line   62:
E474: Invalid argument: listchars=tab:\ \ ,trail:·
Press ENTER or type command to continue
```

[StackOverflow](http://stackoverflow.com/questions/18321538/vim-error-e474-invalid-argument-listchars-tab-trail) says

**Solution**:

Place the following lines at the top of the .vimrc the error mentions:

.vimrc:

```
scriptencoding utf-8
set encoding=utf-8

```

**Comment by Integralist** [comment]
Interesting. So seems the Linux distro you use was causing an issue there (as it's fine on the Mac OS X platform).

So `set encoding` is how the characters are displayed in Vim, but I guess on your platform there was an issue with how it interpreted the character at the end of that line with regards to _parsing_ the vimrc at runtime?

**Comment by Integralist** [comment]
I'm going to close this issue as I don't think it's something I want to add into the .vimrc for all users/platforms when it seems to only affect a select number of users.

But what I've done is added a pointer/reference to this issue (see: https://github.com/Integralist/ProVim/blob/master/.vimrc#L61-L63) so that future users will know where to look and will find your fix. 

Hope that's OK

**Comment by gregorydillon** [comment]
Sure, you are the expert.   But I'm soaking in lots of  new information from the book !!

as a by the way, I'm using Ubuntu 14.04 LTS trusty on a VPS

**Comment by Integralist** [comment]
Glad it's been useful to you :-)
